export type ToolKind="timecard"|"biweekly"|"clockout"|"hoursminutes"|"decimal"|"time";
export type ToolPage={slug:string;title:string;h1:string;description:string;intro:string;kind:ToolKind;copy:string};
export const pages:ToolPage[]=[
{slug:"hours-calculator",title:"Hours Calculator",h1:"Hours Calculator",description:"Free hours calculator for adding work hours, breaks and weekly totals.",intro:"Calculate work hours from clock-in and clock-out times, including unpaid breaks.",kind:"timecard",copy:"Total a work week without manually converting minutes to decimals. Enter each day's start and end time and any unpaid break."},
{slug:"time-card-calculator",title:"Time Card Calculator",h1:"Time Card Calculator",description:"Free time card calculator with breaks, overtime and estimated gross pay.",intro:"Calculate a complete weekly time card with breaks, overtime and estimated pay.",kind:"timecard",copy:"This calculator totals daily work periods, deducts unpaid breaks and shows an optional overtime and gross-pay estimate."},
{slug:"work-hours-calculator",title:"Work Hours Calculator",h1:"Work Hours Calculator",description:"Calculate weekly work hours, breaks, overtime and estimated pay online.",intro:"Add your clock times and get clear daily and weekly work-hour totals.",kind:"timecard",copy:"Designed for employees, contractors and anyone who needs a quick weekly total. AM/PM and overnight shifts are supported."},
{slug:"time-clock-calculator",title:"Time Clock Calculator",h1:"Time Clock Calculator",description:"Free time clock calculator for clock-in, clock-out, breaks and weekly hours.",intro:"Turn daily punches into clear work-hour totals.",kind:"timecard",copy:"Enter time-clock punches for each day to calculate elapsed paid time after break deductions."},
{slug:"time-duration-calculator",title:"Time Duration Calculator",h1:"Time Duration Calculator",description:"Calculate the duration between two times instantly, including overnight periods.",intro:"Find the exact hours and minutes between a start time and an end time.",kind:"time",copy:"Enter two clock times to calculate the elapsed duration. If the end time is earlier than the start time, HourTotals treats it as the following day."},
{slug:"clock-out-time-calculator",title:"Clock Out Time Calculator",h1:"Clock Out Time Calculator",description:"Find what time to clock out from your start time, target hours and unpaid break.",intro:"Enter when you started, how long you need to work and your break. Get your clock-out time instantly.",kind:"clockout",copy:"Adds your target work duration and unpaid break to your start time to calculate when your shift should end."},
{slug:"hours-minutes-calculator",title:"Hours & Minutes Calculator",h1:"Hours & Minutes Calculator",description:"Add or subtract hours and minutes with a free online time calculator.",intro:"Add and subtract time without converting minutes by hand.",kind:"hoursminutes",copy:"Use this calculator for elapsed durations, schedules and calculations involving hours and minutes."},
{slug:"decimal-time-calculator",title:"Decimal Time Calculator",h1:"Decimal Time Calculator",description:"Convert hours and minutes to decimal hours or decimal hours back to time.",intro:"Convert standard time and decimal hours in either direction.",kind:"decimal",copy:"Decimal hours are common in timesheets and payroll exports. For example, 7 hours 45 minutes equals 7.75 decimal hours."},
{slug:"time-card-calculator-with-lunch",title:"Time Card Calculator With Lunch",h1:"Time Card Calculator With Lunch",description:"Calculate weekly time cards with lunch and unpaid break deductions.",intro:"Enter your shifts and lunch duration to calculate paid hours automatically.",kind:"timecard",copy:"Use the break field for an unpaid lunch or other unpaid break. It is deducted before daily and weekly totals are calculated."},
{slug:"biweekly-time-card-calculator",title:"Biweekly Time Card Calculator",h1:"Biweekly Time Card Calculator",description:"Free two-week time card calculator with breaks, weekly overtime estimates and pay.",intro:"Calculate 14 days of work hours from one simple biweekly time card.",kind:"biweekly",copy:"The biweekly calculator totals fourteen daily rows. The optional overtime estimate is calculated independently for each seven-day workweek using a 40-hour threshold."}
];export const pageMap=Object.fromEntries(pages.map(p=>[p.slug,p])) as Record<string,ToolPage>;