"use client";
import {useMemo,useState} from "react";import {clock,decimal,defaultRows,hm,parseTime,worked,type Row} from "@/lib/time";
export function TimeCard({biweekly=false}:{biweekly?:boolean}){const initial=()=>biweekly?[...defaultRows(),...defaultRows().map(r=>({...r,day:`Week 2 · ${r.day}`}))]:defaultRows();const [rows,setRows]=useState<Row[]>(initial);const [rate,setRate]=useState(20);const totals=useMemo(()=>{const each=rows.map(r=>worked(r.clockIn,r.clockOut,r.breakMinutes)),total=each.reduce((a,b)=>a+b,0),regular=Math.min(total,(biweekly?80:40)*60),ot=Math.max(0,total-regular);return{each,total,regular,ot,pay:regular/60*rate+ot/60*rate*1.5}},[rows,rate,biweekly]);const patch=(i:number,p:Partial<Row>)=>setRows(x=>x.map((r,j)=>j===i?{...r,...p}:r));return <div className="panel"><div className="panelHead"><div><h2>{biweekly?"Biweekly":"Weekly"} time card</h2><p>Enter clock times and unpaid breaks. Overnight shifts work too.</p></div><span className="safe">Private · browser only</span></div><div className="scroll"><table><thead><tr><th>Day</th><th>Clock in</th><th>Clock out</th><th>Break</th><th>Total</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td><b>{r.day}</b></td><td><input value={r.clockIn} onChange={e=>patch(i,{clockIn:e.target.value})}/></td><td><input value={r.clockOut} onChange={e=>patch(i,{clockOut:e.target.value})}/></td><td><input type="number" min="0" value={r.breakMinutes} onChange={e=>patch(i,{breakMinutes:+e.target.value})}/></td><td><b>{hm(totals.each[i])}</b></td></tr>)}</tbody></table></div><div className="controls"><label>Hourly rate ($)<input type="number" min="0" step=".01" value={rate} onChange={e=>setRate(+e.target.value)}/></label><div><button className="ghost" onClick={()=>setRows(initial())}>Reset</button><button onClick={()=>window.print()}>Print / Save PDF</button></div></div><div className="stats"><Stat l="Total hours" v={hm(totals.total)}/><Stat l="Decimal" v={decimal(totals.total)}/><Stat l="Overtime" v={hm(totals.ot)}/><Stat l="Est. gross pay" v={`$${totals.pay.toFixed(2)}`}/></div></div>}
function Stat({l,v}:{l:string;v:string}){return <div className="stat"><span>{l}</span><strong>{v}</strong></div>}
export function ClockOut(){const[start,setStart]=useState("8:17 AM"),[hours,setHours]=useState(8),[mins,setMins]=useState(0),[br,setBr]=useState(30);const s=parseTime(start),out=s===null?null:s+hours*60+mins+br;return <Simple title="When should I clock out?"><div className="fields four"><Field label="Clock in"><input value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Target hours"><input type="number" value={hours} onChange={e=>setHours(+e.target.value)}/></Field><Field label="Extra minutes"><input type="number" value={mins} onChange={e=>setMins(+e.target.value)}/></Field><Field label="Unpaid break"><input type="number" value={br} onChange={e=>setBr(+e.target.value)}/></Field></div><Result label="Clock out at" value={out===null?"Enter a valid time":clock(out)}/></Simple>}
export function HoursMinutes(){const[aH,setAH]=useState(7),[aM,setAM]=useState(45),[bH,setBH]=useState(2),[bM,setBM]=useState(30),[op,setOp]=useState("+");const n=aH*60+aM+(op==="+"?1:-1)*(bH*60+bM);return <Simple title="Add or subtract hours & minutes"><div className="fields"><Field label="Hours"><input type="number" value={aH} onChange={e=>setAH(+e.target.value)}/></Field><Field label="Minutes"><input type="number" value={aM} onChange={e=>setAM(+e.target.value)}/></Field><Field label="Operation"><select value={op} onChange={e=>setOp(e.target.value)}><option>+</option><option>-</option></select></Field><Field label="Hours"><input type="number" value={bH} onChange={e=>setBH(+e.target.value)}/></Field><Field label="Minutes"><input type="number" value={bM} onChange={e=>setBM(+e.target.value)}/></Field></div><Result label="Result" value={hm(n)}/></Simple>}
export function DecimalTime(){const[h,setH]=useState(7),[m,setM]=useState(45),[d,setD]=useState(7.75);return <div className="dual"><Simple title="Hours & minutes → decimal"><div className="fields"><Field label="Hours"><input type="number" value={h} onChange={e=>setH(+e.target.value)}/></Field><Field label="Minutes"><input type="number" value={m} onChange={e=>setM(+e.target.value)}/></Field></div><Result label="Decimal hours" value={decimal(h*60+m)}/></Simple><Simple title="Decimal → hours & minutes"><div className="fields"><Field label="Decimal hours"><input type="number" step=".01" value={d} onChange={e=>setD(+e.target.value)}/></Field></div><Result label="Standard time" value={hm(d*60)}/></Simple></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Simple({title,children}:{title:string;children:React.ReactNode}){return <div className="panel simple"><div className="panelHead"><h2>{title}</h2><span className="safe">Instant result</span></div>{children}</div>}
function Result({label,value}:{label:string;value:string}){return <div className="result"><span>{label}</span><strong>{value}</strong></div>}
