"use client";
import {useMemo,useState} from "react";
import {clock,decimal,defaultRows,hm,parseTime,worked,type Row} from "@/lib/time";

export function TimeCalculator(){
 const [start,setStart]=useState("08:35"),[end,setEnd]=useState("17:20");
 const mins=worked(start,end,0);
 return <div className="panel calculatorPanel"><div className="panelHead"><div><span className="eyebrow">TIME DIFFERENCE</span><h2>Calculate time between two times</h2><p>Enter a start and end time. Overnight times are supported automatically.</p></div><span className="safe">Instant · Private</span></div><div className="timeCalcBody"><div className="timeCalcFields"><Field label="Start time"><input type="time" value={start} onChange={e=>setStart(e.target.value)}/></Field><span className="toArrow">→</span><Field label="End time"><input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></Field></div><div className="heroResult"><span>TOTAL DURATION</span><strong>{hm(mins)}</strong><small>{decimal(mins)} decimal hours · {mins} minutes</small></div></div></div>
}
export function TimeCard({biweekly=false}:{biweekly?:boolean}){
 const initial=()=>biweekly?[...defaultRows().map(r=>({...r,day:`Week 1 · ${r.day}`})),...defaultRows().map(r=>({...r,day:`Week 2 · ${r.day}`}))]:defaultRows();
 const [rows,setRows]=useState<Row[]>(initial); const [rate,setRate]=useState(20);
 const totals=useMemo(()=>{const each=rows.map(r=>worked(r.clockIn,r.clockOut,r.breakMinutes)); const total=each.reduce((a,b)=>a+b,0);
 const weeks=biweekly?[each.slice(0,7),each.slice(7,14)]:[each]; let regular=0,ot=0;
 for(const w of weeks){const t=w.reduce((a,b)=>a+b,0);regular+=Math.min(t,2400);ot+=Math.max(0,t-2400)}
 return{each,total,regular,ot,pay:regular/60*rate+ot/60*rate*1.5}},[rows,rate,biweekly]);
 const patch=(i:number,p:Partial<Row>)=>setRows(x=>x.map((r,j)=>j===i?{...r,...p}:r));
 const applyWeekdays=()=>setRows(x=>x.map((r,i)=>{const d=i%7;return d<5?{...r,clockIn:x[0].clockIn||"08:00",clockOut:x[0].clockOut||"17:00",breakMinutes:x[0].breakMinutes}:r}));
 return <div className="panel calculatorPanel"><div className="panelHead"><div><span className="eyebrow">WORK HOURS</span><h2>{biweekly?"Biweekly":"Weekly"} time card</h2><p>Enter clock times and unpaid breaks. Overnight shifts work too.</p></div><span className="safe">Private · browser only</span></div><div className="scroll"><table><thead><tr><th>Day</th><th>Clock in</th><th>Clock out</th><th>Break (min)</th><th>Total</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td><b>{r.day}</b></td><td><input type="time" value={r.clockIn} onChange={e=>patch(i,{clockIn:e.target.value})}/></td><td><input type="time" value={r.clockOut} onChange={e=>patch(i,{clockOut:e.target.value})}/></td><td><input type="number" inputMode="numeric" min="0" value={r.breakMinutes} onChange={e=>patch(i,{breakMinutes:+e.target.value})}/></td><td><b className="dailyTotal">{hm(totals.each[i])}</b></td></tr>)}</tbody></table></div><div className="controls"><label>Hourly rate <span className="moneyInput">$ <input type="number" min="0" step=".01" value={rate} onChange={e=>setRate(+e.target.value)}/></span></label><div><button className="ghost" onClick={applyWeekdays}>Apply Mon–Fri</button><button className="ghost" onClick={()=>setRows(initial())}>Reset</button><button onClick={()=>window.print()}>Print / Save PDF</button></div></div><div className="stats"><Stat l="Total hours" v={hm(totals.total)}/><Stat l="Decimal hours" v={decimal(totals.total)}/><Stat l="Overtime estimate" v={hm(totals.ot)}/><Stat l="Estimated gross pay" v={`$${totals.pay.toFixed(2)}`}/></div><p className="legalNote">Overtime is estimated separately for each 7-day workweek using a 40-hour threshold and 1.5× rate. Actual payroll and legal treatment may differ.</p></div>
}
function Stat({l,v}:{l:string;v:string}){return <div className="stat"><span>{l}</span><strong>{v}</strong></div>}
export function ClockOut(){const[start,setStart]=useState("08:17"),[hours,setHours]=useState(8),[mins,setMins]=useState(0),[br,setBr]=useState(30);const s=parseTime(start),out=s===null?null:s+hours*60+mins+br;return <Simple title="When should I clock out?"><div className="fields four"><Field label="Clock in"><input type="time" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Target hours"><input type="number" value={hours} onChange={e=>setHours(+e.target.value)}/></Field><Field label="Extra minutes"><input type="number" value={mins} onChange={e=>setMins(+e.target.value)}/></Field><Field label="Unpaid break"><input type="number" value={br} onChange={e=>setBr(+e.target.value)}/></Field></div><Result label="CLOCK OUT AT" value={out===null?"Enter a valid time":clock(out)}/></Simple>}
export function HoursMinutes(){const[aH,setAH]=useState(7),[aM,setAM]=useState(45),[bH,setBH]=useState(2),[bM,setBM]=useState(30),[op,setOp]=useState("+");const n=aH*60+aM+(op==="+"?1:-1)*(bH*60+bM);return <Simple title="Add or subtract hours & minutes"><div className="fields"><Field label="Hours"><input type="number" value={aH} onChange={e=>setAH(+e.target.value)}/></Field><Field label="Minutes"><input type="number" value={aM} onChange={e=>setAM(+e.target.value)}/></Field><Field label="Operation"><select value={op} onChange={e=>setOp(e.target.value)}><option>+</option><option>-</option></select></Field><Field label="Hours"><input type="number" value={bH} onChange={e=>setBH(+e.target.value)}/></Field><Field label="Minutes"><input type="number" value={bM} onChange={e=>setBM(+e.target.value)}/></Field></div><Result label="RESULT" value={hm(n)}/></Simple>}
export function DecimalTime(){const[h,setH]=useState(7),[m,setM]=useState(45),[d,setD]=useState(7.75);return <div className="dual"><Simple title="Hours & minutes → decimal"><div className="fields"><Field label="Hours"><input type="number" value={h} onChange={e=>setH(+e.target.value)}/></Field><Field label="Minutes"><input type="number" value={m} onChange={e=>setM(+e.target.value)}/></Field></div><Result label="DECIMAL HOURS" value={decimal(h*60+m)}/></Simple><Simple title="Decimal → hours & minutes"><div className="fields"><Field label="Decimal hours"><input type="number" step=".01" value={d} onChange={e=>setD(+e.target.value)}/></Field></div><Result label="STANDARD TIME" value={hm(d*60)}/></Simple></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Simple({title,children}:{title:string;children:React.ReactNode}){return <div className="panel simple calculatorPanel"><div className="panelHead"><div><span className="eyebrow">FREE CALCULATOR</span><h2>{title}</h2></div><span className="safe">Instant result</span></div>{children}</div>}
function Result({label,value}:{label:string;value:string}){return <div className="result"><span>{label}</span><strong>{value}</strong></div>}
