"use client";
import {useMemo,useState} from "react";
import {clock,decimal,defaultRows,hm,parseTime,worked,type Row} from "@/lib/time";

export function TimeCalculator(){
 const [start,setStart]=useState("08:35"),[end,setEnd]=useState("17:20");
 const mins=worked(start,end,0);
 return <div className="panel calculatorPanel"><div className="panelHead"><div><span className="eyebrow">TIME DIFFERENCE</span><h2>Calculate time between two times</h2><p>Enter a start and end time. Overnight times are supported automatically.</p></div><span className="safe">Instant · Private</span></div><div className="timeCalcBody"><div className="timeCalcFields"><Field label="Start time"><input type="time" value={start} onChange={e=>setStart(e.target.value)}/></Field><span className="toArrow">→</span><Field label="End time"><input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></Field></div><div className="heroResult"><span>TOTAL DURATION</span><strong>{hm(mins)}</strong><small>{decimal(mins)} decimal hours · {mins} minutes</small></div></div></div>
}
export function TimeCard({biweekly=false}:{biweekly?:boolean}){
 const initial=()=>biweekly?[...defaultRows().map(r=>({...r,day:`Week 1 · ${r.day}`})),...defaultRows().map(r=>({...r,day:`Week 2 · ${r.day}`}))]:defaultRows();
 const [rows,setRows]=useState<Row[]>(initial); const [rate,setRate]=useState(20);
 const totals=useMemo(()=>{const each=rows.map(r=>worked(r.clockIn,r.clockOut,r.breakMinutes)); const total=each.reduce((a,b)=>a+b,0);
 const weeks=biweekly?[each.slice(0,7),each.slice(7,14)]:[each]; let regular=0,ot=0;
 for(const w of weeks){const t=w.reduce((a,b)=>a+b,0);regular+=Math.min(t,2400);ot+=Math.max(0,t-2400)}
 return{each,total,regular,ot,pay:regular/60*rate+ot/60*rate*1.5}},[rows,rate,biweekly]);
 const patch=(i:number,p:Partial<Row>)=>setRows(x=>x.map((r,j)=>j===i?{...r,...p}:r));
 const applyWeekdays=()=>setRows(x=>x.map((r,i)=>{const d=i%7;return d<5?{...r,clockIn:x[0].clockIn||"08:00",clockOut:x[0].clockOut||"17:00",breakMinutes:x[0].breakMinutes}:r}));
 return <div className="panel calculatorPanel"><div className="panelHead"><div><span className="eyebrow">WORK HOURS</span><h2>{biweekly?"Biweekly":"Weekly"} time card</h2><p>Enter clock times and unpaid breaks. Overnight shifts work too.</p></div><span className="safe">Private · browser only</span></div><div className="scroll"><table><thead><tr><th>Day</th><th>Clock in</th><th>Clock out</th><th>Break (min)</th><th>Total</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td><b>{r.day}</b></td><td><input type="time" value={r.clockIn} onChange={e=>patch(i,{clockIn:e.target.value})}/></td><td><input type="time" value={r.clockOut} onChange={e=>patch(i,{clockOut:e.target.value})}/></td><td><input type="number" inputMode="numeric" min="0" value={r.breakMinutes} onChange={e=>patch(i,{breakMinutes:+e.target.value})}/></td><td><b className="dailyTotal">{hm(totals.each[i])}</b>{r.clockIn&&r.clockOut&&r.breakMinutes>worked(r.clockIn,r.clockOut,0)?<small className="inputWarning">Break exceeds shift</small>:null}</td></tr>)}</tbody></table></div><div className="controls"><label>Hourly rate <span className="moneyInput">$ <input type="number" min="0" step=".01" value={rate} onChange={e=>setRate(+e.target.value)}/></span></label><div><button className="ghost" onClick={applyWeekdays}>Apply Mon–Fri</button><button className="ghost" onClick={()=>setRows(initial())}>Reset</button><button onClick={()=>window.print()}>Print / Save PDF</button></div></div><div className="stats"><Stat l="Total hours" v={hm(totals.total)}/><Stat l="Decimal hours" v={decimal(totals.total)}/><Stat l="Overtime estimate" v={hm(totals.ot)}/><Stat l="Estimated gross pay" v={`$${totals.pay.toFixed(2)}`}/></div><p className="legalNote">Overtime is estimated separately for each 7-day workweek using a 40-hour threshold and 1.5× rate. Actual payroll and legal treatment may differ.</p></div>
}
function Stat({l,v}:{l:string;v:string}){return <div className="stat"><span>{l}</span><strong>{v}</strong></div>}
export function ClockOut(){const[start,setStart]=useState("08:17"),[hours,setHours]=useState(8),[mins,setMins]=useState(0),[br,setBr]=useState(30);const s=parseTime(start),out=s===null?null:s+hours*60+mins+br;return <Simple title="When should I clock out?"><div className="fields four"><Field label="Clock in"><input type="time" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Target hours"><input type="number" min="0" value={hours} onChange={e=>setHours(Math.max(0,+e.target.value))}/></Field><Field label="Extra minutes"><input type="number" min="0" value={mins} onChange={e=>setMins(Math.max(0,+e.target.value))}/></Field><Field label="Unpaid break"><input type="number" min="0" value={br} onChange={e=>setBr(Math.max(0,+e.target.value))}/></Field></div><Result label="CLOCK OUT AT" value={out===null?"Enter a valid time":clock(out)}/></Simple>}
export function HoursMinutes(){const[aH,setAH]=useState(7),[aM,setAM]=useState(45),[bH,setBH]=useState(2),[bM,setBM]=useState(30),[op,setOp]=useState("+");const n=aH*60+aM+(op==="+"?1:-1)*(bH*60+bM);return <Simple title="Add or subtract hours & minutes"><div className="fields"><Field label="Hours"><input type="number" value={aH} onChange={e=>setAH(+e.target.value)}/></Field><Field label="Minutes"><input type="number" value={aM} onChange={e=>setAM(+e.target.value)}/></Field><Field label="Operation"><select value={op} onChange={e=>setOp(e.target.value)}><option>+</option><option>-</option></select></Field><Field label="Hours"><input type="number" value={bH} onChange={e=>setBH(+e.target.value)}/></Field><Field label="Minutes"><input type="number" value={bM} onChange={e=>setBM(+e.target.value)}/></Field></div><Result label="RESULT" value={hm(n)}/></Simple>}
export function DecimalTime(){const[h,setH]=useState(7),[m,setM]=useState(45),[d,setD]=useState(7.75);return <div className="dual"><Simple title="Hours & minutes → decimal"><div className="fields"><Field label="Hours"><input type="number" value={h} onChange={e=>setH(+e.target.value)}/></Field><Field label="Minutes"><input type="number" value={m} onChange={e=>setM(+e.target.value)}/></Field></div><Result label="DECIMAL HOURS" value={decimal(h*60+m)}/></Simple><Simple title="Decimal → hours & minutes"><div className="fields"><Field label="Decimal hours"><input type="number" step=".01" value={d} onChange={e=>setD(+e.target.value)}/></Field></div><Result label="STANDARD TIME" value={hm(d*60)}/></Simple></div>}
export function ElapsedTime(){const[start,setStart]=useState("09:15"),[end,setEnd]=useState("14:45");const mins=worked(start,end,0);return <Simple title="Calculate elapsed time"><div className="fields"><Field label="Start time"><input type="time" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="End time"><input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></Field></div><Result label="ELAPSED TIME" value={hm(mins)}/><div className="stats"><Stat l="Decimal hours" v={decimal(mins)}/><Stat l="Total minutes" v={String(mins)}/></div></Simple>}

export function PtoTime(){const[balance,setBalance]=useState(80),[used,setUsed]=useState(16),[planned,setPlanned]=useState(8),[day,setDay]=useState(8);const remaining=Math.max(0,balance-used-planned),days=day>0?remaining/day:0;return <Simple title="Calculate remaining PTO time"><div className="fields four"><Field label="PTO balance (hours)"><input type="number" min="0" step=".25" value={balance} onChange={e=>setBalance(Math.max(0,+e.target.value))}/></Field><Field label="PTO already used"><input type="number" min="0" step=".25" value={used} onChange={e=>setUsed(Math.max(0,+e.target.value))}/></Field><Field label="Planned PTO"><input type="number" min="0" step=".25" value={planned} onChange={e=>setPlanned(Math.max(0,+e.target.value))}/></Field><Field label="Hours per workday"><input type="number" min=".25" step=".25" value={day} onChange={e=>setDay(Math.max(.25,+e.target.value))}/></Field></div><Result label="REMAINING PTO" value={`${remaining.toFixed(2)} hours`}/><div className="stats"><Stat l="Available workdays" v={days.toFixed(2)}/><Stat l="Hours accounted for" v={(used+planned).toFixed(2)}/></div></Simple>}

export function VacationHours(){const[current,setCurrent]=useState(40),[accrual,setAccrual]=useState(4),[periods,setPeriods]=useState(6),[planned,setPlanned]=useState(16),[day,setDay]=useState(8);const earned=accrual*periods,projected=Math.max(0,current+earned-planned),days=day>0?projected/day:0;return <Simple title="Project vacation hours"><div className="fields"><Field label="Current hours"><input type="number" min="0" step=".25" value={current} onChange={e=>setCurrent(Math.max(0,+e.target.value))}/></Field><Field label="Hours earned per period"><input type="number" min="0" step=".25" value={accrual} onChange={e=>setAccrual(Math.max(0,+e.target.value))}/></Field><Field label="Periods until target date"><input type="number" min="0" step="1" value={periods} onChange={e=>setPeriods(Math.max(0,+e.target.value))}/></Field><Field label="Planned vacation hours"><input type="number" min="0" step=".25" value={planned} onChange={e=>setPlanned(Math.max(0,+e.target.value))}/></Field><Field label="Hours per workday"><input type="number" min=".25" step=".25" value={day} onChange={e=>setDay(Math.max(.25,+e.target.value))}/></Field></div><Result label="PROJECTED VACATION BALANCE" value={`${projected.toFixed(2)} hours`}/><div className="stats"><Stat l="Hours earned" v={earned.toFixed(2)}/><Stat l="Equivalent workdays" v={days.toFixed(2)}/></div></Simple>}

export function OvertimeCalculator(){const[hours,setHours]=useState(45),[rate,setRate]=useState(20),[threshold,setThreshold]=useState(40),[mult,setMult]=useState(1.5);const regular=Math.min(Math.max(0,hours),Math.max(0,threshold)),ot=Math.max(0,hours-threshold),regularPay=regular*rate,otPay=ot*rate*mult;return <Simple title="Estimate overtime hours and pay"><div className="fields four"><Field label="Total hours worked"><input type="number" min="0" step=".25" value={hours} onChange={e=>setHours(Math.max(0,+e.target.value))}/></Field><Field label="Hourly rate ($)"><input type="number" min="0" step=".01" value={rate} onChange={e=>setRate(Math.max(0,+e.target.value))}/></Field><Field label="Overtime after (hours)"><input type="number" min="0" step=".25" value={threshold} onChange={e=>setThreshold(Math.max(0,+e.target.value))}/></Field><Field label="Overtime multiplier"><input type="number" min="1" step=".1" value={mult} onChange={e=>setMult(Math.max(1,+e.target.value))}/></Field></div><Result label="ESTIMATED GROSS PAY" value={`${(regularPay+otPay).toFixed(2)}`}/><div className="stats"><Stat l="Regular hours" v={regular.toFixed(2)}/><Stat l="Overtime hours" v={ot.toFixed(2)}/><Stat l="Regular pay" v={`${regularPay.toFixed(2)}`}/><Stat l="Overtime pay" v={`${otPay.toFixed(2)}`}/></div><p className="legalNote">This is an arithmetic estimate using the threshold and multiplier you enter. It does not determine overtime eligibility or the legally required regular rate.</p></Simple>}

export function PtoAccrual(){const[start,setStart]=useState(24),[per,setPer]=useState(3.08),[periods,setPeriods]=useState(10),[used,setUsed]=useState(8),[day,setDay]=useState(8);const earned=per*periods,balance=Math.max(0,start+earned-used);return <Simple title="Project PTO accrual"><div className="fields"><Field label="Starting PTO hours"><input type="number" min="0" step=".01" value={start} onChange={e=>setStart(Math.max(0,+e.target.value))}/></Field><Field label="Hours accrued per period"><input type="number" min="0" step=".01" value={per} onChange={e=>setPer(Math.max(0,+e.target.value))}/></Field><Field label="Number of accrual periods"><input type="number" min="0" step="1" value={periods} onChange={e=>setPeriods(Math.max(0,+e.target.value))}/></Field><Field label="PTO used during period"><input type="number" min="0" step=".25" value={used} onChange={e=>setUsed(Math.max(0,+e.target.value))}/></Field><Field label="Hours per workday"><input type="number" min=".25" step=".25" value={day} onChange={e=>setDay(Math.max(.25,+e.target.value))}/></Field></div><Result label="PROJECTED PTO BALANCE" value={`${balance.toFixed(2)} hours`}/><div className="stats"><Stat l="PTO accrued" v={earned.toFixed(2)}/><Stat l="Equivalent days" v={(balance/day).toFixed(2)}/></div><p className="legalNote">Use the accrual rate and policy rules supplied by your employer. Caps, carryover, waiting periods and eligibility are not applied automatically.</p></Simple>}

export function AddTime(){const[h1,setH1]=useState(1),[m1,setM1]=useState(45),[h2,setH2]=useState(2),[m2,setM2]=useState(30),[h3,setH3]=useState(0),[m3,setM3]=useState(50);const total=Math.max(0,h1*60+m1+h2*60+m2+h3*60+m3);return <Simple title="Add multiple time durations"><div className="fields"><Field label="Duration 1 hours"><input type="number" min="0" value={h1} onChange={e=>setH1(Math.max(0,+e.target.value))}/></Field><Field label="Duration 1 minutes"><input type="number" min="0" value={m1} onChange={e=>setM1(Math.max(0,+e.target.value))}/></Field><Field label="Duration 2 hours"><input type="number" min="0" value={h2} onChange={e=>setH2(Math.max(0,+e.target.value))}/></Field><Field label="Duration 2 minutes"><input type="number" min="0" value={m2} onChange={e=>setM2(Math.max(0,+e.target.value))}/></Field><Field label="Duration 3 hours"><input type="number" min="0" value={h3} onChange={e=>setH3(Math.max(0,+e.target.value))}/></Field><Field label="Duration 3 minutes"><input type="number" min="0" value={m3} onChange={e=>setM3(Math.max(0,+e.target.value))}/></Field></div><Result label="TOTAL TIME" value={hm(total)}/><div className="stats"><Stat l="Decimal hours" v={decimal(total)}/><Stat l="Total minutes" v={String(total)}/></div></Simple>}

export function AverageTime(){const[a,setA]=useState(30),[b,setB]=useState(45),[d,setD]=useState(50),[e,setE]=useState(35),[g,setG]=useState(40);const vals=[a,b,d,e,g].map(x=>Math.max(0,x));const avg=vals.reduce((x,y)=>x+y,0)/vals.length;return <Simple title="Find the average time"><p className="legalNote">Enter five durations in minutes. Use 90 for 1 hour 30 minutes.</p><div className="fields">{vals.map((v,i)=><Field key={i} label={`Duration ${i+1} (minutes)`}><input type="number" min="0" value={v} onChange={ev=>{const n=Math.max(0,+ev.target.value);[setA,setB,setD,setE,setG][i](n)}}/></Field>)}</div><Result label="AVERAGE TIME" value={hm(avg)}/><div className="stats"><Stat l="Average minutes" v={avg.toFixed(2)}/><Stat l="Decimal hours" v={decimal(avg)}/></div></Simple>}

export function BillableHours(){const[workedHours,setWorkedHours]=useState(40),[billable,setBillable]=useState(30),[rate,setRate]=useState(100),[collection,setCollection]=useState(100);const safeBillable=Math.min(Math.max(0,billable),Math.max(0,workedHours)),util=workedHours>0?safeBillable/workedHours*100:0,gross=safeBillable*rate,collected=gross*Math.max(0,collection)/100;return <Simple title="Calculate billable hours and value"><div className="fields four"><Field label="Total hours worked"><input type="number" min="0" step=".25" value={workedHours} onChange={e=>setWorkedHours(Math.max(0,+e.target.value))}/></Field><Field label="Billable hours"><input type="number" min="0" step=".25" value={billable} onChange={e=>setBillable(Math.max(0,+e.target.value))}/></Field><Field label="Billing rate ($/hour)"><input type="number" min="0" step=".01" value={rate} onChange={e=>setRate(Math.max(0,+e.target.value))}/></Field><Field label="Collection estimate (%)"><input type="number" min="0" step="1" value={collection} onChange={e=>setCollection(Math.max(0,+e.target.value))}/></Field></div><Result label="BILLABLE VALUE" value={`${gross.toFixed(2)}`}/><div className="stats"><Stat l="Billable utilization" v={`${util.toFixed(1)}%`}/><Stat l="Non-billable hours" v={Math.max(0,workedHours-safeBillable).toFixed(2)}/><Stat l="Estimated collected" v={`${collected.toFixed(2)}`}/></div></Simple>}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Simple({title,children}:{title:string;children:React.ReactNode}){return <div className="panel simple calculatorPanel"><div className="panelHead"><div><span className="eyebrow">FREE CALCULATOR</span><h2>{title}</h2></div><span className="safe">Instant result</span></div>{children}</div>}
function Result({label,value}:{label:string;value:string}){return <div className="result"><span>{label}</span><strong>{value}</strong></div>}
